### ISSUE TITLE
size mismatch between checkpoint and model

### ISSUE THREAD

**Issue by Hannieliao** [qiuqiangkong/panns_inference#15]
Thanks for your amazing work!
During the reasoning process, I ran into a problem: 

panns_inference verison: 0.1.0
checkpoint: Cnn14_16k_mAP=0.438.pth
RuntimeError: Error(s) in loading state_dict for Cnn14:
        size mismatch for fc_audioset.weight: copying a param with shape torch.Size([527, 2048]) from checkpoint, the shape in current model is torch.Size([0, 2048]).
        size mismatch for fc_audioset.bias: copying a param with shape torch.Size([527]) from checkpoint, the shape in current model is torch.Size([0]).

**Comment by nizarhotmail** [comment]
Any updates on this issue yet?
