### ISSUE TITLE
ERROR - code is too big

### ISSUE THREAD

**Issue by shiyu22** [qiuqiangkong/panns_inference#4]
When I run panns-reference with CPU, it shows "ERROR - code is too big".

Is panns-reference only available on GPU? Why does this error occur when using the CPU?

**Comment by qiuqiangkong** [comment]
Hi, PANNs inference can be run on CPU. This may cause from there is no
enough memory. Try to reduce your input duration, for example, 1s second as
input?

**Comment by shiyu22** [comment]
Thanks for your replay, I solved this issue with [pytorch](https://github.com/pytorch/pytorch/issues/24174).
